### ISSUE TITLE
AttributeError: type object ‘datetime.time’ has no attribute 'fromisoformat’

### ISSUE THREAD

**Issue by amutaher** [frappe/chat#6]
**AttributeError: type object ‘datetime.time’ has no attribute 'fromisoformat’**

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 67, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1198, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/chat/chat/api/config.py", line 21, in settings
    config = {**config, **get_chat_settings()}
  File "/home/frappe/frappe-bench/apps/chat/chat/utils/__init__.py", line 89, in get_chat_settings
    start_time = datetime.time.fromisoformat(chat_settings.start_time)
AttributeError: type object 'datetime.time' has no attribute 'fromisoformat'

```

**Comment by codescientist703** [comment]
Please upgrade your python version to 3.7
